### ISSUE TITLE
Add Theme

### ISSUE THREAD

**Issue by noob-master147** [noob-master147/Spin-It-ElectronJS-App#1]
Add a Themes menu in the app
This functionality will provide to toggle between the themes

**Comment by Rajdeepc** [comment]
@noob-master147 Can you please assign this to me? I would like to contribute

**Comment by noob-master147** [comment]
yeah sure @Rajdeepc

**Comment by Rajdeepc** [comment]
@noob-master147  Getting the below error doing npm install
```
RequestError: unable to get local issuer certificate
    at ClientRequest.<anonymous> (C:\Users\RajDChandra\Documents\hacktoberfest\Spin-It-ElectronJS-App\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:323:22)
    at ClientRequest.origin.emit (C:\Users\RajDChandra\Documents\hacktoberfest\Spin-It-ElectronJS-App\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm WARN spinbot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@9.2.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@9.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RajDChandra\AppData\Roaming\npm-cache\_logs\2020-10-01T12_57_20_613Z-debug.log
```

**Comment by noob-master147** [comment]
I pushed a commit on master, pull again and let me know.
